### Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
a = np.arange(2,51,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

### Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
a = [int(i)for i in input().split()]
b = [int(i)for i in input().split()]
a1 = np.array(a)
b1 = np.array(b)
c1 = np.concatenate([a1,b1])
print("Concatenation of two arrays :",c1)
print("Array after sorted :",np.sort(c1))

1 6 7 2 8
3 9 4 10 5
Concatenation of two arrays : [ 1  6  7  2  8  3  9  4 10  5]
Array after sorted : [ 1  2  3  4  5  6  7  8  9 10]


### Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array shape :",a.shape)
print("Array size :",a.size)

Array shape : (3, 3)
Array size : 9


### Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [4]:
a = np.array([1,2,3,4,5])
print("Array shape before conversion :",a.shape)
a = np.expand_dims(a,axis=1)
print("Array shape after conversion :",a.shape)

Array shape before conversion : (5,)
Array shape after conversion : (5, 1)


### Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("H STACK :\n",np.hstack((a,b)))
print("V STACK :\n",np.vstack((a,b)))

H STACK :
 [[1 2 5 6]
 [3 4 7 8]]
V STACK :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Questions 6:
How to get unique items and counts of unique items?

In [6]:
a = np.array([1,2,3,2,4,5,1,3,8,7,6,4])
unique, counts = np.unique(a,return_counts=True)
print(np.asarray((unique, counts)).T)

[[1 2]
 [2 2]
 [3 2]
 [4 2]
 [5 1]
 [6 1]
 [7 1]
 [8 1]]
